name : frontend CI

on :
  push : 
    branches: ["main"]
  pull_request:
    branches : ["main"]

jobs : 
  build:
    runs-on: ubuntu-latest

    steps:
      -name : checkout action
        uses: actions/checkout@v3
      -name: build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push : true
          tags : test/test-frontend:latest